settings:
  units: 
    position: 'm' # m (meter), mm (millimeter)
    orientation: 'euler_degrees' # euler_degrees, euler_radians, quaternion

  controlled_frame: 'tool0'

  # Path tolerance (set to null for default)
  path_tolerance: null
    #position_error: [0.001, 0.001 ,0.001] #[x,y,z]
    #orientation_error: [0.01, 0.01 ,0.01] #[x,y,z]
    #twist_error:
    #  linear:  [0.001, 0.001 ,0.001] #[x,y,z]
    #  angular:  [0.01, 0.01 ,0.01] #[x,y,z]
    #acceleration_error:
    #  linear:  [0.001, 0.001 ,0.001] #[x,y,z]
    #  angular:  [0.01, 0.01 ,0.01] #[x,y,z]

  # Goal tolerance (set to null for default)
  goal_tolerance: null
    #position_error: [0.001, 0.001 ,0.001] #[x,y,z]
    #orientation_error: [0.01, 0.01 ,0.01] #[x,y,z]
    #twist_error:
    #  linear:  [0.001, 0.001 ,0.001] #[x,y,z]
    #  angular:  [0.01, 0.01 ,0.01] #[x,y,z]
    #acceleration_error:
    #  linear:  [0.001, 0.001 ,0.001] #[x,y,z]
    #  angular:  [0.01, 0.01 ,0.01] #[x,y,z]

  # Time tolerance (set to null for default)
  goal_time_tolerance: null

trajectory:
  - time: 0.0
    position: [-0.100, -0.600, 0.200]
    orientation: [180,0,180]
    #linear_velocity:
    #angular_velocity:
  - time: 1.0
    position: [-0.100, -0.600, 0.100]
    orientation: [180,0,180]

  - time: 4.0
    position: [-0.100, -0.600, 0.100]
    orientation: [180,0,180]
  
  - time: 6.0
    position: [-0.100, -0.600, 0.300]
    orientation: [180,0,180]
  
  - time: 6.5
    position: [-0.100, -0.600, 0.300]
    orientation: [180,0,90]

  - time: 7.0
    position: [-0.300, -0.500, 0.300]
    orientation: [180,0,90]
  
  - time: 8.0
    position: [-0.300, -0.500, 0.200]
    orientation: [180,0,90]

  - time: 11.0
    position: [-0.300, -0.500, 0.200]
    orientation: [180,0,90]
    
  - time: 11.5
    position: [-0.300, -0.500, 0.200]
    orientation: [180,0,90]

  - time: 12.0
    position: [-0.300, -0.500, 0.300]
    orientation: [180,0,90]